# Uncomment the next line to define a global platform for your project
platform :ios, '15.4'

target 'Daangn-Market' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Daangn-Market
  pod 'Alamofire'
  pod 'Kingfisher'
  pod 'ImagePicker'
end
